src/WF.Find.Presentation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WF.Find.Presentation.Services;
using Microsoft.AspNet.Identity;

namespace WF.Find.Presentation.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GenerateGuid()
        {
            Guid id = Guid.NewGuid();
            var result = new { id = id };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SendEmail(string email, string nome)
        {
            string assunto = "Convite Find";
            var callbackUrl = Url.Action("Index", "Home", null, protocol: Request.Url.Scheme);

            string corpo = "Olá " + nome + " você foi convidado para uma partida de Find " +
                "clique  <a href=\"" + callbackUrl + "\">AQUI</a> para jogar";

            IdentityMessage message = new IdentityMessage();
            EmailService sendEmail = new EmailService();
            message.Destination = email;
            message.Subject = assunto;
            message.Body = corpo;

            try
            {
                sendEmail.SendAsync(message);
                var result = new { send = true };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                var result = new { send = false };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

src/WF.Find.Presentation/Controllers/findawayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WF.Find.Presentation.Controllers
{
    public class findawayController : Controller
    {
        public ActionResult easy()
        {
            var caminho = ObterCaminhoEasy(null, 0);
            return View();
        }

        public ActionResult normal()
        {
            var caminho = ObterCaminho(5, 3);
            Session["caminho"] = caminho;
            return View();
        }

        public ActionResult hard()
        {
            var caminho = ObterCaminho(7, 4);
            Session["caminho"] = caminho;
            return View();
        }

        public List<int> ObterCaminho(int totStep, int option)
        {
            List<int> caminho = new List<int>();
            Random rand = new Random();
            int coluna = 0;
            int step = 0;
            int colunaMaxima = option;
            int colunaMinima = 0;

            while (step < totStep)
            {
                if (step == 0)
                {
                    coluna = rand.Next(colunaMinima, colunaMaxima + 1);
                    caminho.Add(coluna);
                    step++;
                }
                else
                {
                    if (caminho.ElementAt(step - 1) == colunaMinima)
                    {
                        coluna = rand.Next(0, colunaMinima + 1);
                        caminho.Add(coluna);
                        step++;
                    }
                    else if (caminho.ElementAt(step - 1) == colunaMaxima)
                    {
                        coluna = rand.Next(colunaMaxima - 1, colunaMaxima + 1);
                        caminho.Add(coluna);
                        step++;
                    }
                    else if (caminho.ElementAt(step - 1) != colunaMaxima && caminho.ElementAt(step - 1) != colunaMinima)
                    {
                        coluna = rand.Next(caminho.ElementAt(step - 1) - 1, caminho.ElementAt(step - 1) + 2);
                        caminho.Add(coluna);
                        step++;
                    }
                }
            }
            return caminho;

        }

        public List<PathEasy> ObterCaminhoEasy(int? value, int step)
        {
            List<PathEasy> caminho = new List<PathEasy>();
            PathEasy cam = new PathEasy();
            Random rand = new Random();
            int coluna = 0;
            int colunaMaxima = 3;
            int colunaMinima = 0;

            if (string.IsNullOrEmpty(value.ToString()))
            {

                coluna = rand.Next(colunaMinima, colunaMaxima);
                cam.option1 = coluna;

                while (coluna == cam.option1)
                {
                    coluna = rand.Next(colunaMinima, colunaMaxima);
                }

                cam.option2 = coluna;
            }
            else
            {
                caminho = Session["caminho"] as List<PathEasy>;
                if (value == colunaMinima)
                {
                    cam.option1 = colunaMinima;
                    cam.option2 = colunaMinima + 1;
                }
                else if (value == colunaMaxima - 1)
                {
                    cam.option1 = colunaMaxima - 1;
                    cam.option2 = colunaMinima + 1;
                }
                else
                {
                    coluna = rand.Next(colunaMinima, colunaMaxima);
                    cam.option1 = coluna;

                    while (coluna == cam.option1)
                    {
                        coluna = rand.Next(colunaMinima, colunaMaxima);
                    }

                    cam.option2 = coluna;
                }
            }
            caminho.Add(cam);
            Session["caminho"] = caminho;
            return caminho;
        }

        public JsonResult ObterProximoEasy(int Step, int value)
        {
            var caminho = Session["caminho"] as List<PathEasy>;

            if (caminho.ElementAt(Step).option1 == value || caminho.ElementAt(Step).option2 == value)
            {
                if (Step < 3)
                {
                    caminho = ObterCaminhoEasy(value, Step);
                }
                return Json(new { prox = true }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { prox = false }, JsonRequestBehavior.AllowGet);


        }
        public JsonResult ObterProximo(int Step, int value)
        {
            var caminho = Session["caminho"] as List<int>;
            if (caminho.ElementAt(Step) == value)
                return Json(new { prox = true }, JsonRequestBehavior.AllowGet);
            else
                return Json(new { prox = false }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ObterTodos()
        {
            var caminho = Session["caminho"] as List<int>;
            var result = new { todos = caminho };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ObterTodosEasy(int step)
        {
            var caminho = Session["caminho"] as List<PathEasy>;
            while (step < 2)
            {
                var cam = ObterCaminhoEasy(null, step);
                caminho.Add(cam.ElementAt(0));
                step++;
            }
            var result = new { todos = caminho };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
    public class PathEasy
    {
        public int option1 { get; set; }
        public int option2 { get; set; }
    }
}

src/WF.Find.Presentation/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<style>
    .easy {
        margin-bottom: 1%;
    }

    .normal {
        margin-bottom: 1%;
    }

    .btn {
        width: 30%;
    }
</style>
<h1 class="page-header">Find</h1>
<hr />
<div class="row easy">
    <div class="col-xs-12 col-md-offset-4">
        @Html.ActionLink("Easy", "easy", "findaway", null, new { @class = "btn btn-primary" })
    </div>
</div>

<div class="row normal">
    <div class="col-xs-12 col-md-offset-4">
        @Html.ActionLink("Normal", "normal", "findaway", null, new { @class = "btn btn-primary" })
    </div>
</div>

<div class="row hard">
    <div class="col-xs-12 col-md-offset-4">
        @Html.ActionLink("Hard", "hard", "findaway", null, new { @class = "btn btn-primary" })
    </div>
</div>

src/WF.Find.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Find", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">

        <div class="modal" id="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 id="hd" class="modal-title"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p id="txt"></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" onclick="recarregar()">Try again</button>
                        <button type="button" class="btn btn-primary" onclick="compartilhar()"><span class="tooltiptext" id="myTooltip">Share Stage</span></button>
                        <button type="button" class="btn btn-primary" onclick="convite()">Invite a Friend</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal" id="modalEmail" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Invite</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" id="name">
                            </div>
                            <div class="form-group">
                                <label for="message-text" class="col-form-label">Email:</label>
                                <input type="text" class="form-control" id="email">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary cancel" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" onclick="sendEmail()">Send message</button>
                    </div>
                </div>
            </div>
        </div>

        @RenderBody()
        <hr />

        <footer>
            <p>&copy; @DateTime.Now.Year - Find ASP.NET</p>
        </footer>
    </div>
    <script>
        $(".cancel").click(function () {
            $(".modal").hide();
        });
        $(".close").click(function () {
            $(".modal").hide();
        });

        function recarregar() {
            $('#modal').hide();
            location.reload();
        }

        function compartilhar() {
            var location = window.location.href;

            var id = "";
            $.ajax({
                url: "/Home/GenerateGuid",
                method: "POST",
                async: false,
            }).done(function (result) {
                id = result.id;
                });

            var URL = location + "/" + id;            

            var tooltip = document.getElementById("myTooltip");
            tooltip.innerHTML = "Copied to clipboard ";
        }

        function convite() {
            $('#modal').hide();
            $('#modalEmail').show();
        }

        function sendEmail() {
            var nome = $('#name').val();
            var email = $('#email').val();
            var send = false;
            $.ajax({
                url: "/Home/SendEmail",
                method: "POST",
                data: { email: email, nome: nome },
                async: false,
            }).done(function (result) {
                send = result.send;
                });

            if (send) {
                $('#modalEmail').hide();
                alert("Convite enviado com sucesso!");
                location.reload();
            }

            if (!send) {
                $('#modalEmail').hide();
                alert("Não foi posssivel enviar o convite");
                location.reload();
            }
        }

    </script>

</body>
</html>

src/WF.Find.Presentation/Views/findaway/easy.cshtml
@{
    ViewBag.Title = "easy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="page-header">Easy</h1>
<hr />
<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-3">
        <table class="game">
            <thead>
                <tr>
                    <th class="vazio"></th>
                    <th colspan="3" class="header">Side A</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < 3; i++)
                {
                    string step = "step" + i;
                    int value = i + 1;
                    <tr id="@step">
                        <td class="step">Step @value</td>
                        @for (int j = 0; j <3; j++)
                        {
                            if (i == 0)
                            {
                                <td><button id="@j" class="btn btn-info path">?</button></td>
                            }
                            else
                            {
                                <td id="cel_@j"><button id="@j" class="btn btn-info path" disabled>?</button></td>
                            }

                        }
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th class="vazio"></th>
                    <th colspan="3" class="header">Side B</th>
                </tr>
            </tfoot>
        </table>
        
    </div>
</div>

<script>
    var step = 0;
    var prox;    
    var todos = [];
    
    $(document).ready(function () {
        $(".path").click(function () {
            var value = "";            
            value = $(this).get(0).id;

            $.ajax({
                url: "/findaway/ObterProximoEasy",
                method: "POST",
                async: false,
                data: { step: step, value:value },
            }).done(function (result) {
                prox = result.prox;                
            });

           
            if (step == 0) {
                $(".path").text('');
            }


            if (prox) {
                step++;
                $(this).text('V');
                $(this).css("background-color", "green");
                var td = $("#step" + step + "> td > :button");
                $(td).each(function () {
                    $(this).removeAttr('disabled');
                });
                if (step == 3) {
                    $("#hd").text("Parabéns");
                    $("#txt").text("Parabéns, isso foi muito difícil.");
                    $('#modal').show();
                }
            } else {

                $.ajax({
                    url: "/findaway/ObterTodosEasy",
                    type: 'POST',
                    data: { step: step},
                    async: false,
                }).done(function (result) {
                    todos = result.todos;

                });
                $(this).text('X');
                $(this).css("color", "red");
                var stepRest = 3 - step;
                for (step; step < 3; step++) {
                    var td = $("#step" + step + "> td > :button");
                    $(td).each(function () {
                        if ($(this).get(0).id == todos[step].option1 || $(this).get(0).id == todos[step].option2) {
                            $(this).text('V');
                            $(this).css("background-color", "green");
                            return;
                        }
                    });
                }
                $("#hd").text("Haaa que pena");
                $("#txt").text("Oh não, apenas a " + stepRest + " passos de distância.");
                $('#modal').show();
            }
        });
    });
</script>

src/WF.Find.Presentation/Views/findaway/hard.cshtml
@{
    ViewBag.Title = "hard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="page-header">Hard</h1>
<hr />
<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-3">
        <table class="game">
            <thead>
                <tr>
                    <th class="vazio"></th>
                    <th colspan="5" class="header">Side A</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < 7; i++)
                {
                    string step = "step" + i;
                    int value = i + 1;
                    <tr id="@step">
                        <td class="step">Step @value</td>
                        @for (int j = 0; j < 5; j++)
                        {
                            if (i == 0)
                            {
                                <td><button id="@j" class="btn btn-info path">?</button></td>
                            }
                            else
                            {
                                <td id="cel_@j"><button id="@j" class="btn btn-info path" disabled>?</button></td>
                            }

                        }
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th class="vazio"></th>
                    <th colspan="5" class="header">Side B</th>
                </tr>
            </tfoot>
        </table>        
    </div>
</div>

<script>
    var step = 0;
    var prox;
    var todos = [];

   
    $(document).ready(function () {
        $(".path").click(function () {

            var value = "";
            value = $(this).get(0).id;

            $.ajax({
                url: "/findaway/ObterProximo",
                method: "POST",
                async: false,
                data: { step: step, value: value },
            }).done(function (result) {
                prox = result.prox;
            });

            if (step == 0) {
                $(".path").text('');
            }


            if (prox) {
                step++;
                $(this).text('V');
                $(this).css("background-color", "green");
                var td = $("#step" + step + "> td > :button");
                $(td).each(function () {
                    $(this).removeAttr('disabled');
                });
                if (step == 7) {
                    $("#hd").text("Parabéns");
                    $("#txt").text("Parabéns, isso foi muito difícil.");
                    $('#modal').show();
                }
            } else {

                $.ajax({
                    url: "/findaway/ObterTodos",
                    type: 'POST',
                    async: false,
                }).done(function (result) {
                    todos = result.todos;

                });
                $(this).text('X');
                $(this).css("color", "red");
                var stepRest = 7 - step;
                for (step; step < 7; step++) {
                    var td = $("#step" + step + "> td > :button");
                    $(td).each(function () {
                        if ($(this).get(0).id == todos[step]) {
                            $(this).text('V');
                            $(this).css("background-color", "green");
                            return;
                        }
                    });
                }
                $("#hd").text("Haaa que pena");
                $("#txt").text("Oh não, apenas a " + stepRest + " passos de distância.");
                $('#modal').show();
            }
        });
    });
</script>

src/WF.Find.Presentation/Views/findaway/normal.cshtml
@{
    ViewBag.Title = "normal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="page-header">Normal</h1>
<hr />
<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-3">
        <table class="game">
            <thead>
                <tr>
                    <th class="vazio"></th>
                    <th colspan="4" class="header">Side A</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < 5; i++)
                {
                    string step = "step" + i;
                    int value = i + 1;
                    <tr id="@step">
                        <td class="step">Step @value</td>
                        @for (int j = 0; j < 4; j++)
                        {
                            if (i == 0)
                            {
                                <td><button id="@j" class="btn btn-info path">?</button></td>
                            }
                            else
                            {
                                <td id="cel_@j"><button id="@j" class="btn btn-info path" disabled>?</button></td>
                            }

                        }
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th class="vazio"></th>
                    <th colspan="4" class="header">Side B</th>
                </tr>
            </tfoot>
        </table>        
    </div>
</div>

<script>
    var step = 0;
    var prox;
    var todos = [];
    
    $(document).ready(function () {
        $(".path").click(function () {

            var value = "";
            value = $(this).get(0).id;

            $.ajax({
            url: "/findaway/ObterProximo",
            method: "POST",
            async: false,
            data: { step: step, value: value },
        }).done(function (result) {
            prox = result.prox;
        });
            
            if (step == 0) {
                $(".path").text('');            }


            if (prox) {
                step++;
                $(this).text('V');
                $(this).css("background-color", "green");
                var td = $("#step" + step + "> td > :button");
                $(td).each(function () {
                    $(this).removeAttr('disabled');
                });
                if (step == 5) {
                    $("#hd").text("Parabéns");
                    $("#txt").text("Parabéns, isso foi muito difícil.");
                    $('#modal').show();
                }
            } else {

                $.ajax({
                    url: "/findaway/ObterTodos",
                    type: 'POST',
                    async: false,
                }).done(function (result) {
                    todos = result.todos;

                });
                $(this).text('X');
                $(this).css("color", "red");
                var stepRest = 5 - step;
                for (step; step < 6; step++) {
                    var td = $("#step" + step + "> td > :button");
                    $(td).each(function () {
                        if ($(this).get(0).id == todos[step]) {
                            $(this).text('V');
                            $(this).css("background-color", "green");
                            return;
                        }
                    });
                }
                $("#hd").text("Haaa que pena");
                $("#txt").text("Oh não, apenas a " + stepRest + " passos de distância.");
                $('#modal').show();
            }
        });
    });
</script>